config/routes.rb
Rails.application.routes.draw do
  root 'preposition_verbs#home', as: :home

  resources :preposition_verbs only: [:index, :new, :create]

end

app/models/preposition_verb.rb
class PrepositionVerb < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/preposition_verbs_controller.rb
class PrepositionVerbsController < ApplicationController
  def home
  end

  def index
    @verbs = PrepositionVerb.all
  end

  def new
    @preposition_verb = PrepositionVerb.new
  end

  def create
    @preposition_verb = PrepositionVerb.new(verb_params)
    @preposition_verb.save
    redirect_to preposition_verbs_path
  end

  def play
    @verb = PrepositionVerb.all.sort_by{rand}.first
  end

  def play_translation
    @verb = PrepositionVerb.all.sort_by{rand}.first
    @guess = params[:guess]
  end

  private

  def verb_params
    params.require(:preposition_verb).permit(:verb, :translation, :preposition, :sentence_with_blank)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/preposition_verbs_helper.rb
module PrepositionVerbsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Verbs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/preposition_verbs/home.html.erb
<h1>Welcome to the Preposition Verbs Practice Arena</h1>

<%= link_to "Verb List", preposition_verbs_path %>
<%= link_to "Add verb", new_preposition_verb_path %>

<h2>Play!</h2>
<h3><%= link_to "PLAY!", play_path %></h3>
<h3><%= link_to "Try translations", play_translation_path %></h3>

app/views/preposition_verbs/index.html.erb
<h1>Preposition Verbs</h1>
<% @verbs.each do |prep_verb| %>
  <h2><%= prep_verb.verb %></h2>
  <ul>
    <li>translation: <%= prep_verb.translation %></li>
    <li>preposition: <%= prep_verb.preposition %></li>
    <li><%= prep_verb.sentence_with_blank %></li>
  </ul>
<% end %>
<%= link_to "home", home_path %>

app/views/preposition_verbs/new.html.erb
<h1>Add a new verb</h1>
<%= form_for(@preposition_verb) do |f| %>
  <p>
    <%= f.label :verb %>
    <%= f.text_field :verb %>
  </p>
  <p>
    <%= f.label :translation %>
    <%= f.text_field :translation %>
  </p>
  <p>
    <%= f.label :preposition %>
    <%= f.text_field :preposition %>
  </p>
  <p>
    <%= f.label :sentence_with_blank %>
    <%= f.text_field :sentence_with_blank %>
  </p>
  <%= f.submit %>
<% end %>
<%= link_to "Home", home_path %>

app/views/preposition_verbs/play.html.erb
<h1><%= @verb.verb %></h1>

app/views/preposition_verbs/play_translation.html.erb
<h1><%= @verb.verb %></h1>
<form action="/play/translation" method="get">
  <label for="guess">Enter English translation</label>
  <input type="text" name="guess">
  <input type="hidden" value=<%=@verb%>>
  <input type="submit">
</form>